# Embeds compiled SPIR-V modules into a generated header.
#
# Shaders ship inside the binary rather than as loose files, so a deployed build
# cannot be pointed at a modified shader on disk.

file(GLOB SPIRV_FILES "${SPIRV_DIR}/*.spv")
list(SORT SPIRV_FILES)

set(CONTENT "// Generated by embed_shaders.cmake. Do not edit.\n")
string(APPEND CONTENT "#pragma once\n\n")
string(APPEND CONTENT "#include <cstdint>\n#include <span>\n#include <string_view>\n\n")
string(APPEND CONTENT "namespace mivw::render::shaders {\n\n")

set(REGISTRY "")

foreach(SPIRV ${SPIRV_FILES})
    get_filename_component(NAME ${SPIRV} NAME_WE)
    get_filename_component(FULL ${SPIRV} NAME)
    string(REPLACE "." "_" SYMBOL ${FULL})
    string(REPLACE "-" "_" SYMBOL ${SYMBOL})

    file(READ ${SPIRV} HEX HEX)
    string(REGEX MATCHALL "([A-Fa-f0-9][A-Fa-f0-9])" BYTES ${HEX})

    # SPIR-V is a stream of 32-bit words; emit it as such so alignment is
    # guaranteed without a runtime memcpy.
    list(LENGTH BYTES BYTE_COUNT)
    math(EXPR WORD_COUNT "${BYTE_COUNT} / 4")

    string(APPEND CONTENT "inline constexpr std::uint32_t ${SYMBOL}[] = {\n   ")
    set(COLUMN 0)
    foreach(WORD_INDEX RANGE 1 ${WORD_COUNT})
        math(EXPR I0 "(${WORD_INDEX} - 1) * 4")
        math(EXPR I1 "${I0} + 1")
        math(EXPR I2 "${I0} + 2")
        math(EXPR I3 "${I0} + 3")
        list(GET BYTES ${I0} B0)
        list(GET BYTES ${I1} B1)
        list(GET BYTES ${I2} B2)
        list(GET BYTES ${I3} B3)

        # Little-endian assembly.
        string(APPEND CONTENT " 0x${B3}${B2}${B1}${B0},")

        math(EXPR COLUMN "${COLUMN} + 1")
        if(COLUMN EQUAL 6)
            string(APPEND CONTENT "\n   ")
            set(COLUMN 0)
        endif()
    endforeach()
    string(APPEND CONTENT "\n};\n\n")

    string(APPEND REGISTRY "    if (name == \"${FULL}\") return {${SYMBOL}, ${WORD_COUNT}};\n")
endforeach()

string(APPEND CONTENT "[[nodiscard]] inline std::span<const std::uint32_t> find(std::string_view name) {\n")
string(APPEND CONTENT "${REGISTRY}")
string(APPEND CONTENT "    return {};\n}\n\n")
string(APPEND CONTENT "}  // namespace mivw::render::shaders\n")

file(WRITE ${OUTPUT} "${CONTENT}")
message(STATUS "Embedded ${SPIRV_FILES} into ${OUTPUT}")
